### ISSUE TITLE
강의평 db

### ISSUE THREAD

**Issue by yubinlee** [estanie/dbproject#6]
CREATE TABLE BOARD(
	num NUMBER(10) AUTO_INCREMENT CONSTRAINT b_pk PRIMARY KEY,
	username VARCHAR(20),
	password VARCHAR(20),
	title VARCHAR(20) NOT NULL,
	memo VARCHAR(500),
	hit NUMBER(10)
);

CREATE TABLE COMENTTABLE(
id VARCHAR(20),
content VARCHAR(100),
ref NUMBER(10)
);

**Comment by estanie** [comment]
CREATE TABLE BOARD(
num NUMBER(10) CONSTRAINT b_pk PRIMARY KEY,
username VARCHAR(20),
password VARCHAR(20),
title VARCHAR(20) NOT NULL,
memo VARCHAR(500),
hit NUMBER(10)
);

CREATE SEQUENCE num
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999999999;

CREATE TABLE COMENTTABLE(
id VARCHAR(20),
content VARCHAR(100),
ref NUMBER(10)
);

로 수정!
