### ISSUE TITLE
디비수정

### ISSUE THREAD

**Issue by yubinlee** [estanie/dbproject#7]
CREATE SEQUENCE num
START WITH 1
INCREMENT BY 1

CREATE TABLE BOARD(
	num NUMBER(10) T b_pk PRIMARY KEY,
	username VARCHAR(20),
	password VARCHAR(20),
	title VARCHAR(20) NOT NULL,
	memo VARCHAR(500),
	hit NUMBER(10)
);

**Comment by estanie** [comment]
CREATE TABLE STUDENTS (
    s_id NUMBER(10) CONSTRAINT s_pk PRIMARY KEY,
    s_pwd VARCHAR(20),
    s_name VARCHAR(10),
    s_major VARCHAR(20),
    s_addr VARCHAR(30),
    s_email VARCHAR(50)
 );
 
 CREATE TABLE PROFESSOR (
    p_id NUMBER(10) CONSTRAINT p_pk PRIMARY KEY,
    p_pwd VARCHAR(20),
    p_name VARCHAR(10),
    p_major VARCHAR(20),
    p_email VARCHAR(50)
 );
 
 CREATE TABLE COURSE (
    c_id VARCHAR(4),
    c_id_no NUMBER(2),
    c_unit NUMBER(1),
    c_name VARCHAR(30),
    CONSTRAINT c_pk PRIMARY KEY(c_id, c_id_no) 
 );
 
CREATE TABLE teach (
    c_id VARCHAR(4),
    c_id_no NUMBER(2) ,
    p_id NUMBER(10),
    t_year NUMBER(4),
    t_semester NUMBER(1),
    t_time NUMBER(2),--월/수, 화,목, 금 교시
    t_day NUMBER(1), --1 : 월/수, 2: 화/목, 3: 금
    t_max NUMBER(3),
    t_where VARCHAR(20),
    CONSTRAINT t_c_id_fk FOREIGN KEY (c_id,c_id_no) REFERENCES COURSE(c_id,c_id_no),
    CONSTRAINT t_p_id_fk FOREIGN KEY (p_id) REFERENCES PROFESSOR(p_id),
    CONSTRAINT t_pk PRIMARY KEY(p_id, t_time, t_year, t_semester)
 );
 
 CREATE TABLE ENROLL (
    s_id NUMBER(10) ,
    c_id VARCHAR(4),
    c_id_no NUMBER(2),
    e_year NUMBER(4),
    e_semester NUMBER(1),
    CONSTRAINT e_s_id_fk FOREIGN KEY (s_id) REFERENCES STUDENTS(s_id),
    CONSTRAINT e_c_id_fk FOREIGN KEY (c_id,c_id_no) REFERENCES COURSE(c_id,c_id_no),
    CONSTRAINT e_pk PRIMARY KEY(e_year, e_semester, s_id, c_id)
 );
CREATE SEQUENCE b_no
START WITH 1
INCREMENT BY 1;

CREATE TABLE BOARD(
b_no NUMBER(10) CONSTRAINT b_pk PRIMARY KEY,
b_name VARCHAR(20),
b_pwd VARCHAR(20),
b_title VARCHAR(20) NOT NULL,
b_content VARCHAR(1000),
b_regDate VARCHAR(10),
c_id VARCHAR(4),
c_id_no NUMBER(2),
t_year NUMBER(4),
t_semester NUMBER(1),
b_hit NUMBER(10),
CONSTRAINT b_c_id_fk FOREIGN KEY (c_id, c_id_no) REFERENCES COURSE(c_id,c_id_no)
);

CREATE TABLE COMENTTABLE(
id VARCHAR(20),
content VARCHAR(100),
ref NUMBER(10),
CONSTRAINT com_ref_fk FOREIGN KEY (ref) REFERENCES BOARD(b_no)
);
